[package]
name = "tutorial1-window"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tutorial1-window"
path = "src/main.rs"


[dependencies]
bevy = { version = "0.13.0", default-features = false, features = [
  "bevy_asset",
  "bevy_winit",
  "bevy_render",
  "multi-threaded",
] }
